<?php

//generated by laravel sanctrum

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum', 'admin')
->group(function(){
    Route::get('/user', [AuthController::class, 'getUser']);
    Route::post('/logout', [AuthController::class, 'logout']);

    Route::apiResource('/products', ProductController::class);
    Route::apiResource('/categories', CategoryController::class );
});
